Text to speech and speech to text better aayi work cheyyunnundenkil ath ivide last add cheyyaam...

In [102]:
#a = "This is very good"
a = '''No I wasn't getting panic attacks on hearing about it.I haven't felt nervous or anxious as all my family members were with me.I didn't feel lonely but as the lockdown extended
I had felt boredom.Yes,I lost one of my grandparents due to covid.During first diagnosis they said he was covid positive so we weren't able to see him even during his funerals.
But later we realised that he was not affected by covid and his death wasn't because of it.I haven't had any pesonal plans so I can't say that they were changed.Yes,I felt a little
bit hopeless about my exams as the classes were online we never paid much attention to studies,this situation gave me a tension that whether I would pass my final exams.
I don't have a proper answer for it.Yes even now I'm able to enjoy those things.Small problems were there as I couldn't meet my cousins whom I used to meet regularly.But I got
adjusted to the situation as it was a lockdown.Sometimes I cannot cope up with my daily problems.No,I didn't feel mentally weak while interacting with others.
Yes one of my riend came to a depression state as during lockdown she wasn't able to communicate with anyone.She consulted a psychologist and her family suggested us friends to
interact with her.Yes,I felt frustrations during lockdown.First few days of lockdown I enjoyed my holidays but as it extended I felt bored of sitting at home.Yes I lost interest
in studies as the online classes weren't as effective as offline classes.I only studied during the last days of exam which made me stressed.I was worried whether we will get our
remaining college life or will whole college life will be like online mode'''

Sentimental analysis chyth kazhinj nmde words oru array aayittaan result tharunnath...athil negetive,neutral,positive aavn ethra chance und enn aan ullath...Soo athil koodthal ullath aan nmde wordsnte sentiment analysis chyth kittunna better result...

In [103]:
def find_largest(neg, neu, pos):
    if neg >= neu and neg >= pos:
        return {'negetive' : neg}
    elif neu >= neg and neu >= pos:
        return {'neutral' : neu}
    else:
        return {'positive' : pos}




# Sentiment Intensity Analysis (Vader)

In [104]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [45]:
from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

model1 = SentimentIntensityAnalyzer()

In [46]:
model1.polarity_scores("This is very good")

{'neg': 0.0, 'neu': 0.484, 'pos': 0.516, 'compound': 0.4927}

In [47]:
vader_scores = model1.polarity_scores(a)
vader_scores

{'neg': 0.143, 'neu': 0.726, 'pos': 0.131, 'compound': -0.6276}

In [71]:
vader_largest = find_largest(vader_scores['neg'],vader_scores['neu'],vader_scores['pos'])
vader_largest

{'neutral': 0.726}

# RoBERT

In [7]:
!pip install scipy

In [49]:
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from scipy.special import softmax

In [50]:
Model = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(Model)
model = AutoModelForSequenceClassification.from_pretrained(Model)


In [51]:
text_data = tokenizer(a,return_tensors='pt')
text_data

{'input_ids': tensor([[    0,  3084,    38,   938,    75,   562,  9810,  1912,    15,  1576,
            59,    24,     4,   100,  2220,    75,  1299,  7464,    50, 13473,
            25,    70,   127,   284,   453,    58,    19,   162,     4,   100,
           399,    75,   619, 20100,    53,    25,     5, 23076,  3112, 50118,
           100,    56,  1299, 40326,     4,  9904,     6,   100,   685,    65,
             9,   127, 15198,   528,     7, 47268,   808,     4, 14229,    78,
          9726,    51,    26,    37,    21, 47268,   808,  1313,    98,    52,
          3559,    75,   441,     7,   192,   123,   190,   148,    39, 31978,
          1536,     4, 50118,  1708,   423,    52, 11555,    14,    37,    21,
            45,  2132,    30, 47268,   808,     8,    39,   744,   938,    75,
           142,     9,    24,     4,   100,  2220,    75,    56,   143, 12165,
         20171,   708,    98,    38,    64,    75,   224,    14,    51,    58,
          1714,     4,  9904,     6,  

In [52]:
print(text_data['input_ids'])

tensor([[    0,  3084,    38,   938,    75,   562,  9810,  1912,    15,  1576,
            59,    24,     4,   100,  2220,    75,  1299,  7464,    50, 13473,
            25,    70,   127,   284,   453,    58,    19,   162,     4,   100,
           399,    75,   619, 20100,    53,    25,     5, 23076,  3112, 50118,
           100,    56,  1299, 40326,     4,  9904,     6,   100,   685,    65,
             9,   127, 15198,   528,     7, 47268,   808,     4, 14229,    78,
          9726,    51,    26,    37,    21, 47268,   808,  1313,    98,    52,
          3559,    75,   441,     7,   192,   123,   190,   148,    39, 31978,
          1536,     4, 50118,  1708,   423,    52, 11555,    14,    37,    21,
            45,  2132,    30, 47268,   808,     8,    39,   744,   938,    75,
           142,     9,    24,     4,   100,  2220,    75,    56,   143, 12165,
         20171,   708,    98,    38,    64,    75,   224,    14,    51,    58,
          1714,     4,  9904,     6,   100,  1299,  

In [53]:
print(text_data['attention_mask'])

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1

In [55]:
result = model(**text_data)
result
#result[0]

SequenceClassifierOutput(loss=None, logits=tensor([[ 1.1314,  0.2946, -1.5343]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [56]:
result[0]

tensor([[ 1.1314,  0.2946, -1.5343]], grad_fn=<AddmmBackward0>)

In [57]:
score = result[0][0].detach().numpy()
score = softmax(score)
score

array([0.6655043 , 0.28821218, 0.04628352], dtype=float32)

In [58]:
label = {
    'neg' : score[0],
    'neu' : score[1],
    'pos' : score[2]
}

print(label)

{'neg': 0.6655043, 'neu': 0.28821218, 'pos': 0.04628352}


In [72]:
roberta_largest = find_largest(label['neg'],label['neu'],label['pos'])
roberta_largest

{'negetive': 0.6655043}

Total enn oru list create chyth 2 algorithm chytha result append cheyyunnu...Ennt Aa list vach positive aano negetive aano neutral aano enn basic logic vach knd pidikkunnu...

In [118]:

total = []
total.append(list(vader_largest)[0])
total.append(list(roberta_largest)[0])

print("Total scores : \n vader = {0}\n roberta = {1} \n {2}".format(vader_largest,roberta_largest,total))

Total scores : 
 vader = {'neutral': 0.726}
 roberta = {'negetive': 0.6655043} 
 ['neutral', 'negetive']


Positive , negetive , neutralinu okke oro values kodukkunnu...Ennitt aa total list(Comparison result of two models) ulla values vach average nokkunnu.. Aa total listil eettavum aduth nikkunnath eethinod aanenn chech cheyyunnu...

In [117]:
#Oronninum oro values itt kodth nokkunna method........

values = {
    'negetive' : 1 ,
    'neutral' : 2 ,
    'positive' : 3
          }



avg_values = values[total[0]]+values[total[1]]
ans = round(avg_values/2) #---------------> Average value round cheyth edkunnu...
#int(avg_values/2)
print(list(values)[ans-1]) #-------------->
'''Avg value kitti kazhinj aa valuenu corresponding aayittulla key print cheyynm...
So athine list aayi convert chyth kazhinjaal aa keys maathram ulla list kittum...
Then,Athil ninn aa corresponding key index chyth edknm...
Indexing 0 thott ullathkond aan 1 add chythath..(a+1)...
'''

neutral


'Avg value kitti kazhinj aa valuenu corresponding aayittulla key print cheyynm...\nSo athine list aayi convert chyth kazhinjaal aa keys maathram ulla list kittum...\nThen,Athil ninn aa corresponding key index chyth edknm...\nIndexing 0 thott ullathkond aan 1 add chythath..(a+1)...\n'

Ithu veroru method aan...Manually nml vichaarikknapole 2 combination vannal nth aavn aan chance enn list pole kodukkunnu...Ennt nmde 'total' list aayi compare cheyyunnu.. Nmde logicil change cheyynath anusarich result better aakn pattum..

In [109]:
#Total list comparison chyth nokkunna method......
#Ithil neutral-negetive = neutral aayum neutral-positive = positive aayum try cheyyanm...Ennt better one select cheyynm...Or old method

neutral1 = ['neutral','neutral']
negetive1 = [['neutral','negetive'],['negetive','neutral'],['negetive','negetive']]
positive1 = [['positive','positive'],['neutral','positive'],['positive','neutral']]

In [110]:
if total==neutral1:
  print("Neutral")

elif total in negetive1:
  print("Negetive")

else:
  print("Positive")

Negetive


# Ee 2 methodilm eethenkilm oru method vach try chyyaam...

Athpole full paragraph edkaathe sentencewise sentimental analysis cheyth ellathinteem result oru listil add chyth average eduth ath positive aano negetive aano neutral aano enn nokknm...Eee 2 methodsm(Full paragraph,Sentence) nokki nallath enn thonunna orennam edth final implementation aakaam...

Dataset kittmo enn kurach njaan thappiyaarnn..And ath kittvaaneel classical machine learning koode combine chyth cheyyn pattna method njaan nokkaam...Otherwise..,Ith use chyyndi varm..

In [8]:
'''
from transformers import pipeline

classifier = pipeline(task="text-classification", model="SamLowe/roberta-base-go_emotions", top_k=None)

sentences = ["I am not having a great day"]

model_outputs = classifier(sentences)
print(model_outputs[0])
'''


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/380 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

[{'label': 'disappointment', 'score': 0.46669524908065796}, {'label': 'sadness', 'score': 0.398495078086853}, {'label': 'annoyance', 'score': 0.06806596368551254}, {'label': 'neutral', 'score': 0.05703027546405792}, {'label': 'disapproval', 'score': 0.04423932731151581}, {'label': 'nervousness', 'score': 0.014850745908915997}, {'label': 'realization', 'score': 0.014059904962778091}, {'label': 'approval', 'score': 0.011267471127212048}, {'label': 'joy', 'score': 0.006303394213318825}, {'label': 'remorse', 'score': 0.006221492309123278}, {'label': 'caring', 'score': 0.006029406096786261}, {'label': 'embarrassment', 'score': 0.0052654859609901905}, {'label': 'anger', 'score': 0.0049814279191195965}, {'label': 'disgust', 'score': 0.004259033594280481}, {'label': 'grief', 'score': 0.0040021371096372604}, {'label': 'confusion', 'score': 0.003382918192073703}, {'label': 'relief', 'score': 0.0031405005138367414}, {'label': 'desire', 'score': 0.00282747158780694}, {'label': 'admiration', 'score